ROUTINE TREINAMENTOPKG.EXERCICIO2
EXERCICIO2
    Read "Digite o valor de X: ", X
    Read "Digite o valor de Y: ", Y

    Set contador = 0  ; Inicializa o contador

    for a = X:1:Y {
        //if a#2 = 1 {  ; Verifica se é ímpar
        if 'a#2 = 0 {
            Write a, " É ímpar", !  ; Exibe o número ímpar
            Set contador = contador + 1  ; Incrementa o contador
        }
    }

    Write "Quantidade de números ímpares entre ", X, " e ", Y, ": ", contador, !